# syntax=docker/dockerfile:1

FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY app ./app
COPY server ./server
COPY shared ./shared
COPY public ./public
COPY nuxt.config.ts tailwind.config.js tsconfig.json ./

ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG NUXT_PUBLIC_PUSHER_APP_ID
ARG NUXT_PUBLIC_PUSHER_KEY
ARG NUXT_PUBLIC_PUSHER_CLUSTER

ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY
ENV NUXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
ENV NUXT_PUBLIC_SUPABASE_KEY=$SUPABASE_KEY
ENV NUXT_PUBLIC_PUSHER_APP_ID=$NUXT_PUBLIC_PUSHER_APP_ID
ENV NUXT_PUBLIC_PUSHER_KEY=$NUXT_PUBLIC_PUSHER_KEY
ENV NUXT_PUBLIC_PUSHER_CLUSTER=$NUXT_PUBLIC_PUSHER_CLUSTER

RUN npm run build

FROM node:22-alpine AS production

WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=3000

COPY --from=build /app/.output ./.output

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
