-- Endereços do cliente da loja pública (ligados à conversa).
-- Rodar no SQL Editor do Supabase. NÃO executar automaticamente pelo app.

create table if not exists public.enderecos_clientes (
  id bigint generated by default as identity not null,
  conversa_key text not null,
  workspace_id bigint not null,
  id_canal bigint not null,
  rua text not null,
  numero text not null default '',
  complemento text null,
  bairro text not null default '',
  cidade text not null default '',
  uf text not null default '',
  cep text not null default '',
  ponto_referencia text null,
  apelido text null,
  padrao boolean not null default false,
  latitude double precision null,
  longitude double precision null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone null,
  constraint enderecos_clientes_pkey primary key (id),
  constraint enderecos_clientes_conversa_key_fkey
    foreign key (conversa_key) references public.conversas (key)
    on update cascade on delete cascade,
  constraint enderecos_clientes_workspace_id_fkey
    foreign key (workspace_id) references public.workspace (id)
    on update cascade on delete cascade,
  constraint enderecos_clientes_id_canal_fkey
    foreign key (id_canal) references public.canais (id)
    on update cascade on delete cascade
);

comment on table public.enderecos_clientes is
  'Endereços de entrega do cliente da loja pública, ligados a conversas.key.';

comment on column public.enderecos_clientes.conversa_key is
  'Conversa do cliente (public.conversas.key).';

comment on column public.enderecos_clientes.padrao is
  'Se true, é o endereço padrão desta conversa.';

create index if not exists idx_enderecos_clientes_conversa_key
  on public.enderecos_clientes using btree (conversa_key)
  where deleted_at is null;

create index if not exists idx_enderecos_clientes_canal
  on public.enderecos_clientes using btree (id_canal, conversa_key)
  where deleted_at is null;

create index if not exists idx_enderecos_clientes_workspace
  on public.enderecos_clientes using btree (workspace_id)
  where deleted_at is null;

create unique index if not exists enderecos_clientes_padrao_uidx
  on public.enderecos_clientes (conversa_key)
  where padrao = true and deleted_at is null;

revoke all on table public.enderecos_clientes from public;
revoke all on table public.enderecos_clientes from anon;
revoke all on table public.enderecos_clientes from authenticated;
grant all on table public.enderecos_clientes to service_role;
